name: oc_cobot
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.4=hbcca054_0
  - catkin_pkg=1.0.0=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - empy=3.3.4=pyh9f0ad1d_1
  - exceptiongroup=1.2.0=py310h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - lark-parser=0.12.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=12.3.0=hc0a3c3a_7
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pytest=7.4.4=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - boto3==1.34.136
      - botocore==1.34.136
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fonttools==4.53.0
      - fsspec==2024.6.1
      - gymnasium==0.29.1
      - isaacsim==4.1.0.0
      - isaacsim-app==4.1.0.0
      - isaacsim-asset==4.1.0.0
      - isaacsim-benchmark==4.1.0.0
      - isaacsim-code-editor==4.1.0.0
      - isaacsim-core==4.1.0.0
      - isaacsim-cortex==4.1.0.0
      - isaacsim-example==4.1.0.0
      - isaacsim-extscache-kit==4.1.0.0
      - isaacsim-extscache-kit-sdk==4.1.0.0
      - isaacsim-extscache-physics==4.1.0.0
      - isaacsim-gui==4.1.0.0
      - isaacsim-kernel==4.1.0.0
      - isaacsim-replicator==4.1.0.0
      - isaacsim-rl==4.1.0.0
      - isaacsim-robot==4.1.0.0
      - isaacsim-robot-motion==4.1.0.0
      - isaacsim-robot-setup==4.1.0.0
      - isaacsim-ros1==4.1.0.0
      - isaacsim-ros2==4.1.0.0
      - isaacsim-sensor==4.1.0.0
      - isaacsim-storage==4.1.0.0
      - isaacsim-template==4.1.0.0
      - isaacsim-test==4.1.0.0
      - isaacsim-utils==4.1.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - omniverse-kit==106.0.1.126909
      - opencv-python==4.10.0.84
      - osqp==0.6.7.post0
      - pillow==10.3.0
      - pip==24.2
      - psutil==6.0.0
      - pyperclip==1.9.0
      - pyyaml==6.0.1
      - qdldl==0.1.7.post4
      - scipy==1.14.0
      - sympy==1.12.1
      - torch==2.3.1
      - triton==2.3.1
      - urllib3==2.2.2
prefix: /home/bemunin/anaconda3/envs/oc_cobot
